<a href="https://colab.research.google.com/github/nanicoder/pp-ai-ml-2026/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data-sets/binary.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   admit   400 non-null    int64
 1   gre     400 non-null    int64
 2   gpa     400 non-null    float64
 3   rank    400 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 12.6 KB

In [3]:
df.shape

(400, 4)

In [4]:
df.head()

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [5]:
df.tail()

     admit  gre   gpa  rank
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

In [6]:
df.tail(10)

     admit  gre   gpa  rank
390      1  800  3.05     2
391      1  660  3.88     2
392      1  600  3.38     3
393      1  620  3.75     2
394      1  460  3.99     3
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

In [7]:
df.head(-10)

     admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
385      0  420  3.02     1
386      1  740  3.86     2
387      0  580  3.36     2
388      0  640  3.17     2
389      0  640  3.51     2

[390 rows x 4 columns]

In [8]:
df.sample(10)

     admit  gre   gpa  rank
268      1  680  3.46     2
266      0  560  3.24     4
361      1  540  3.49     1
374      0  560  3.78     2
378      0  640  3.12     3
222      1  480  3.02     1
153      0  580  3.46     3
387      0  580  3.36     2
110      0  680  3.08     4
354      1  540  3.78     2

In [9]:
df.columns

Index(['admit', 'gre', 'gpa', 'rank'], dtype='str')

In [10]:
df.describe()

            admit         gre         gpa       rank
count  400.000000  400.000000  400.000000  400.00000
mean     0.317500  587.700000    3.389900    2.48500
std      0.466087  115.516536    0.380567    0.94446
min      0.000000  220.000000    2.260000    1.00000
25%      0.000000  520.000000    3.130000    2.00000
50%      0.000000  580.000000    3.395000    2.00000
75%      1.000000  660.000000    3.670000    3.00000
max      1.000000  800.000000    4.000000    4.00000

In [11]:
# Data Cleaning

## Data Cleaning
- choosing the colums from dataframe
- choosing a single column from a dataframe
- choosing a certain data from dataframe
- choosing a certain condition from dataframe with dual conditions.
- drop/delete the coloumn from the table

In [12]:
df1 = df[['gre', 'gpa']]
df1.shape

(400, 2)

In [13]:
df1.gre

0      380
1      660
2      800
3      640
4      520
      ...
395    620
396    560
397    460
398    700
399    600
Name: gre, Length: 400, dtype: int64

In [14]:
df1.gre > 650

0      False
1       True
2       True
3      False
4      False
       ...
395    False
396    False
397    False
398     True
399    False
Name: gre, Length: 400, dtype: bool

In [15]:
df_gre780 = df1[df1.gre > 780]
df_gre780.shape

(25, 2)

In [16]:
df_gre780_gpa35 = df1[(df1.gre > 780) & (df1.gpa > 3.5)]
df_gre780_gpa35.shape

(17, 2)

In [17]:
df_deleted = df1.drop(['gre'], axis=1)
df_deleted.head()

    gpa
0  3.61
1  3.67
2  4.00
3  3.19
4  2.93

In [18]:
df_renamecol = df1.rename(columns={'gre': 'gre_score'})
df_renamecol.head()

   gre_score   gpa
0        380  3.61
1        660  3.67
2        800  4.00
3        640  3.19
4        520  2.93

In [19]:
#change position of columns
cols = df1[['gpa', 'gre']]  
cols

      gpa  gre
0    3.61  380
1    3.67  660
2    4.00  800
3    3.19  640
4    2.93  520
..    ...  ...
395  4.00  620
396  3.04  560
397  2.63  460
398  3.65  700
399  3.89  600

[400 rows x 2 columns]

In [20]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'gender': ['Female', 'Male', 'Male'],
    'salary': [70000, 80000, 90000]
}

In [21]:
data1 = pd.DataFrame(data)  
data1.insert(0, 'id', range(1, len(data1) + 1))
data1.to_csv('../data-sets/employee_data.csv', index=False)

In [22]:
data1.head()

   id     name  age         city  gender  salary
0   1    Alice   25     New York  Female   70000
1   2      Bob   30  Los Angeles    Male   80000
2   3  Charlie   35      Chicago    Male   90000

In [23]:
sales_data = {
    'product': ['A', 'B', 'C', 'D'],
    'sales': [100, 150, 200, 250],
    'profit': [20, 30, 50, 70]
}
price_data = {
    'product': ['E', 'F', 'G', 'H'],
    'price': [10, 15, 20, 25]
}

In [24]:
new_df = pd.concat([pd.DataFrame(sales_data), pd.DataFrame(price_data)], axis=0)
new_df.head(10)
new_df.to_csv('../data-sets/sales_price_data.csv', index=False)

In [25]:
df_sales_price = pd.read_csv('../data-sets/sales_price_data.csv')
df_sales_price.head()

  product  sales  profit  price
0       A  100.0    20.0    NaN
1       B  150.0    30.0    NaN
2       C  200.0    50.0    NaN
3       D  250.0    70.0    NaN
4       E    NaN     NaN   10.0

In [26]:
df_proddimen = pd.read_csv('../data-sets/proddimen.csv')
df_proddimen.head()

  Product_Category            Product_Sub_Category Prod_id
0  OFFICE SUPPLIES          STORAGE & ORGANIZATION  Prod_1
1  OFFICE SUPPLIES                      APPLIANCES  Prod_2
2  OFFICE SUPPLIES  BINDERS AND BINDER ACCESSORIES  Prod_3
3       TECHNOLOGY    TELEPHONES AND COMMUNICATION  Prod_4
4        FURNITURE              OFFICE FURNISHINGS  Prod_5

In [27]:
df_proddimen.Product_Category.value_counts(normalize=True)

Product_Category
OFFICE SUPPLIES    0.529412
TECHNOLOGY         0.235294
FURNITURE          0.235294
Name: proportion, dtype: float64

In [28]:
df_custdimen = pd.read_csv('../data-sets/custdimen.csv')
df_custdimen.head()

        Customer_Name Province   Region Customer_Segment Cust_id
0  MUHAMMED MACINTYRE  NUNAVUT  NUNAVUT   SMALL BUSINESS  Cust_1
1        BARRY FRENCH  NUNAVUT  NUNAVUT         CONSUMER  Cust_2
2       CLAY ROZENDAL  NUNAVUT  NUNAVUT        CORPORATE  Cust_3
3      CARLOS SOLTERO  NUNAVUT  NUNAVUT         CONSUMER  Cust_4
4        CARL JACKSON  NUNAVUT  NUNAVUT        CORPORATE  Cust_5