<a href="https://colab.research.google.com/github/nanicoder/pp-ai-ml-2026/blob/main/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data-sets/binary.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   admit   400 non-null    int64
 1   gre     400 non-null    int64
 2   gpa     400 non-null    float64
 3   rank    400 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 12.6 KB

In [3]:
df.shape

(400, 4)

In [4]:
df.head()

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

In [5]:
df.tail()

     admit  gre   gpa  rank
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

In [6]:
df.tail(10)

     admit  gre   gpa  rank
390      1  800  3.05     2
391      1  660  3.88     2
392      1  600  3.38     3
393      1  620  3.75     2
394      1  460  3.99     3
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

In [7]:
df.head(-10)

     admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
385      0  420  3.02     1
386      1  740  3.86     2
387      0  580  3.36     2
388      0  640  3.17     2
389      0  640  3.51     2

[390 rows x 4 columns]

In [8]:
df.sample(10)

     admit  gre   gpa  rank
177      1  620  3.23     3
290      1  620  3.45     2
175      1  620  3.37     2
191      0  800  3.54     3
107      0  480  3.13     2
309      0  440  2.98     3
148      1  480  2.91     1
251      0  620  3.21     4
263      1  620  3.95     3
180      0  620  3.78     3

In [9]:
df.columns

Index(['admit', 'gre', 'gpa', 'rank'], dtype='str')

In [10]:
df.describe()

            admit         gre         gpa       rank
count  400.000000  400.000000  400.000000  400.00000
mean     0.317500  587.700000    3.389900    2.48500
std      0.466087  115.516536    0.380567    0.94446
min      0.000000  220.000000    2.260000    1.00000
25%      0.000000  520.000000    3.130000    2.00000
50%      0.000000  580.000000    3.395000    2.00000
75%      1.000000  660.000000    3.670000    3.00000
max      1.000000  800.000000    4.000000    4.00000

In [11]:
# Data Cleaning

## Data Cleaning
- choosing the colums from dataframe
- choosing a single column from a dataframe
- choosing a certain data from dataframe
- choosing a certain condition from dataframe with dual conditions.
- drop/delete the coloumn from the table

In [12]:
df1 = df[['gre', 'gpa']]
df1.shape

(400, 2)

In [13]:
df1.gre

0      380
1      660
2      800
3      640
4      520
      ...
395    620
396    560
397    460
398    700
399    600
Name: gre, Length: 400, dtype: int64

In [14]:
df1.gre > 650

0      False
1       True
2       True
3      False
4      False
       ...
395    False
396    False
397    False
398     True
399    False
Name: gre, Length: 400, dtype: bool

In [15]:
df_gre780 = df1[df1.gre > 780]
df_gre780.shape

(25, 2)

In [16]:
df_gre780_gpa35 = df1[(df1.gre > 780) & (df1.gpa > 3.5)]
df_gre780_gpa35.shape

(17, 2)

In [17]:
df_deleted = df1.drop(['gre'], axis=1)
df_deleted.head()

    gpa
0  3.61
1  3.67
2  4.00
3  3.19
4  2.93

In [18]:
df_renamecol = df1.rename(columns={'gre': 'gre_score'})
df_renamecol.head()

   gre_score   gpa
0        380  3.61
1        660  3.67
2        800  4.00
3        640  3.19
4        520  2.93

In [19]:
#change position of columns
cols = df1[['gpa', 'gre']]  
cols

      gpa  gre
0    3.61  380
1    3.67  660
2    4.00  800
3    3.19  640
4    2.93  520
..    ...  ...
395  4.00  620
396  3.04  560
397  2.63  460
398  3.65  700
399  3.89  600

[400 rows x 2 columns]

In [21]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'city': ['New York', 'Los Angeles', 'Chicago'],
    'gender': ['Female', 'Male', 'Male']
}