<a href="https://colab.research.google.com/github/nanicoder/pp-ai-ml-2026/blob/main/ai-ml-simplilearn/classes/feb222026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df_binarycsv = pd.read_csv('../data-sets/binary.csv')
df_binarycsv.head()

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4

# contents
- iloc
- loc
- renaming index/rows

In [3]:
df_binarycsv.iloc[2:4, 1:3]

   gre   gpa
2  800  4.00
3  640  3.19

In [4]:
df_binarycsv.iloc[:, 1:3]

     gre   gpa
0    380  3.61
1    660  3.67
2    800  4.00
3    640  3.19
4    520  2.93
..   ...   ...
395  620  4.00
396  560  3.04
397  460  2.63
398  700  3.65
399  600  3.89

[400 rows x 2 columns]

In [5]:
df_binarycsv.iloc[[1, 2, 16, 22, 58], 1:3]

    gre   gpa
1   660  3.67
2   800  4.00
16  780  3.87
22  600  2.82
58  400  3.65

In [6]:
df_binarycsv.loc[[1, 2, 16, 22, 58], ['gre', 'rank']]

    gre  rank
1   660     3
2   800     1
16  780     4
22  600     4
58  400     2

In [7]:
df_binarycsv.columns

Index(['admit', 'gre', 'gpa', 'rank'], dtype='str')

In [8]:
df_binarycsv.index

RangeIndex(start=0, stop=400, step=1)

In [9]:
df_binarycsvnew = df_binarycsv.rename(index={0: 'one', 1: 'two', 2: 'three', 3: 'four'})
df_binarycsvnew

       admit  gre   gpa  rank
one        0  380  3.61     3
two        1  660  3.67     3
three      1  800  4.00     1
four       1  640  3.19     4
4          0  520  2.93     4
...      ...  ...   ...   ...
395        0  620  4.00     2
396        0  560  3.04     3
397        0  460  2.63     2
398        0  700  3.65     2
399        0  600  3.89     3

[400 rows x 4 columns]

In [10]:
df_binarycsvnew.rename(columns={'gre': 'gre_score', 'gpa': 'gpa_score', 'rank': 'rank_score'}, inplace=True)
df_binarycsvnew

       admit  gre_score  gpa_score  rank_score
one        0        380       3.61           3
two        1        660       3.67           3
three      1        800       4.00           1
four       1        640       3.19           4
4          0        520       2.93           4
...      ...        ...        ...         ...
395        0        620       4.00           2
396        0        560       3.04           3
397        0        460       2.63           2
398        0        700       3.65           2
399        0        600       3.89           3

[400 rows x 4 columns]

In [11]:
#unique values in a column
df_binarycsvnew['rank_score'].unique()

array([3, 1, 4, 2])

In [12]:
df_binarycsvnew.rank_score.unique()

array([3, 1, 4, 2])

In [14]:
df_binarycsv.nunique()

admit      2
gre       26
gpa      132
rank       4
dtype: int64